// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	scrapper "jusbrasil-tech-challenge/app/scrapper"
)

// ProcessScrapper is an autogenerated mock type for the ProcessScrapper type
type ProcessScrapper struct {
	mock.Mock
}

type ProcessScrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *ProcessScrapper) EXPECT() *ProcessScrapper_Expecter {
	return &ProcessScrapper_Expecter{mock: &_m.Mock}
}

// FetchAndParseCases provides a mock function with given fields: url
func (_m *ProcessScrapper) FetchAndParseCases(url string) ([]scrapper.LegalCase, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for FetchAndParseCases")
	}

	var r0 []scrapper.LegalCase
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]scrapper.LegalCase, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) []scrapper.LegalCase); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scrapper.LegalCase)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessScrapper_FetchAndParseCases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAndParseCases'
type ProcessScrapper_FetchAndParseCases_Call struct {
	*mock.Call
}

// FetchAndParseCases is a helper method to define mock.On call
//   - url string
func (_e *ProcessScrapper_Expecter) FetchAndParseCases(url interface{}) *ProcessScrapper_FetchAndParseCases_Call {
	return &ProcessScrapper_FetchAndParseCases_Call{Call: _e.mock.On("FetchAndParseCases", url)}
}

func (_c *ProcessScrapper_FetchAndParseCases_Call) Run(run func(url string)) *ProcessScrapper_FetchAndParseCases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ProcessScrapper_FetchAndParseCases_Call) Return(_a0 []scrapper.LegalCase, _a1 error) *ProcessScrapper_FetchAndParseCases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProcessScrapper_FetchAndParseCases_Call) RunAndReturn(run func(string) ([]scrapper.LegalCase, error)) *ProcessScrapper_FetchAndParseCases_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessScrapper creates a new instance of ProcessScrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessScrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessScrapper {
	mock := &ProcessScrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
