FROM docker pull golang:1.22.1-alpine

ENV APPLICATION_PACKAGE=./cmd/api \
    APP_PATH=/app \
    APPLICATION_REPO=github.com/wjcaetano/jusbrasil-tech-challenge \

    GO_RACE_DETECTION_ENABLED="true"
