services:
  jusbrasil-tech-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./commands/run_local.sh" ]
    container_name: jusbrasil-tech-challenge
    depends_on:
      testlocal:
        condition: service_healthy
    env_file: resources/config/local.properties
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - $HOME/go/pkg/mod:/go/pkg/mod
    networks:
      - app-network

  testlocal:
    container_name: testlocal
    env_file: resources/config/local.properties
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: testlocal
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  db_data:

networks:
  app-network:
    driver: bridge