// Code generated by mockery v2.49.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ScrapperRepository is an autogenerated mock type for the ScrapperRepository type
type ScrapperRepository struct {
	mock.Mock
}

type ScrapperRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ScrapperRepository) EXPECT() *ScrapperRepository_Expecter {
	return &ScrapperRepository_Expecter{mock: &_m.Mock}
}

// FetchPage provides a mock function with given fields: url
func (_m *ScrapperRepository) FetchPage(url string) (string, error) {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for FetchPage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScrapperRepository_FetchPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPage'
type ScrapperRepository_FetchPage_Call struct {
	*mock.Call
}

// FetchPage is a helper method to define mock.On call
//   - url string
func (_e *ScrapperRepository_Expecter) FetchPage(url interface{}) *ScrapperRepository_FetchPage_Call {
	return &ScrapperRepository_FetchPage_Call{Call: _e.mock.On("FetchPage", url)}
}

func (_c *ScrapperRepository_FetchPage_Call) Run(run func(url string)) *ScrapperRepository_FetchPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ScrapperRepository_FetchPage_Call) Return(_a0 string, _a1 error) *ScrapperRepository_FetchPage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScrapperRepository_FetchPage_Call) RunAndReturn(run func(string) (string, error)) *ScrapperRepository_FetchPage_Call {
	_c.Call.Return(run)
	return _c
}

// NewScrapperRepository creates a new instance of ScrapperRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScrapperRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScrapperRepository {
	mock := &ScrapperRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
